Repository essentialkaos/webkaos, pull requests merged in 2018-09, with the labels that each got.

#69 Version 1.15.3
  SOURCES/webkaos-dynamic-tls-records.patch
  SOURCES/webkaos.patch
  webkaos.spec
Labels: PR • RELEASE

#70 Downgraded BoringSSL version
  webkaos.spec
Labels: PR • FIX

#71 Use apache/incubator-pagespeed-ngx instead of pagespeed/ngx_pagespeed
  SOURCES/incubator-pagespeed-ngx-build-force.patch
  SOURCES/ngx_pagespeed-build-force.patch
  webkaos.spec
Labels: PR • FIX, PR • IMPROVEMENT

#72 Version 1.15.4
  SOURCES/boringssl.patch
  SOURCES/ngx_pagespeed-build-force.patch
  SOURCES/pagespeed-access.pswd
  SOURCES/pagespeed-enabled.conf
  SOURCES/pagespeed.conf
  SOURCES/webkaos-dynamic-tls-records.patch
  SOURCES/webkaos.conf
  SOURCES/webkaos.init
  SOURCES/webkaos.patch
  SOURCES/webkaos.sysconfig
  webkaos.spec
Labels: PR • RELEASE

#73 README updated
  README.md
Labels: PR • RELEASE
